apiVersion: v1
kind: Service
metadata:
  name: rollout-canary-svc
  namespace: rollouts-demo
spec:
  type: LoadBalancer
  selector:
    app: rollout-canary
  ports:
    - name: http
      port: 80
      targetPort: 8080
